export interface SupplementalQuestion {
  id: string;
  level: 'Remember' | 'Understand' | 'Apply' | 'Analyze' | 'Evaluate';
  prompt: string;
  choices: readonly string[];
  answer: number;
  explanation: string;
  hint: string;
  source: string;
}

// Five additional questions per module. Together with the three questions authored
// beside each lesson, these create eight explained, source-mapped questions per module.
export const SUPPLEMENTAL_QUESTIONS: Readonly<Record<string, readonly SupplementalQuestion[]>> = {
  m01: [
    { id: 'm01q4', level: 'Remember', prompt: 'Which operating-system abstraction represents a running program?', choices: ['Directory', 'Process', 'Disk block', 'Page offset'], answer: 1, explanation: 'A process packages a running program with its execution and resource state.', hint: 'Choose the abstraction that owns registers and an address space.', source: 'OSTEP Introduction and Chapter 2' },
    { id: 'm01q5', level: 'Understand', prompt: 'Why is protection part of resource virtualization?', choices: ['It makes every program an administrator', 'It prevents one program from freely corrupting another program or the OS', 'It removes context switches', 'It makes storage volatile'], answer: 1, explanation: 'Useful virtualization must isolate clients while sharing physical resources.', hint: 'Think about what must happen when unrelated programs share one machine.', source: 'OSTEP Chapter 2' },
    { id: 'm01q6', level: 'Apply', prompt: 'A command works only after an undocumented environment change. Which artifact best improves reproducibility?', choices: ['A screenshot without commands', 'A versioned container recipe and exact command', 'A faster processor', 'A larger terminal font'], answer: 1, explanation: 'The recipe and command record dependencies and execution steps another student can repeat.', hint: 'Prefer evidence another person can execute.', source: 'Winter 2026 course setup goals; OSTEP Introduction' },
    { id: 'm01q7', level: 'Analyze', prompt: 'The kernel provides context switching, while the scheduler chooses which process runs. What distinction does this illustrate?', choices: ['Volatile versus persistent', 'Mechanism versus policy', 'Syntax versus linking', 'Polling versus DMA'], answer: 1, explanation: 'Context switching is the enabling mechanism; selection is scheduling policy.', hint: 'One part enables an action and the other chooses among options.', source: 'OSTEP Chapter 2' },
    { id: 'm01q8', level: 'Evaluate', prompt: 'Which environment report provides the strongest evidence that a lab is ready?', choices: ['“It works”', 'OS/tool versions, build command, exit status, output, and one known limitation', 'Only the source filename', 'A copied classmate result'], answer: 1, explanation: 'Reproducible evidence records the environment, action, result, and boundary.', hint: 'Choose the report an instructor could independently diagnose.', source: 'Winter 2026 student-evaluation concern: Docker, Make, and C setup evidence' }
  ],
  m02: [
    { id: 'm02q4', level: 'Remember', prompt: 'Which call lets a parent collect a terminated child?', choices: ['exec', 'wait', 'open', 'mmap'], answer: 1, explanation: 'wait or waitpid synchronizes with child termination and collects its status.', hint: 'The parent uses this after fork.', source: 'OSTEP Chapter 5: Process API' },
    { id: 'm02q5', level: 'Understand', prompt: 'After a successful fork, why can parent and child print different PID values?', choices: ['They are different processes with distinct identities', 'fork disables identifiers', 'exec already ran', 'They share one stack pointer forever'], answer: 0, explanation: 'The child begins from copied logical state but is a separately identified process.', hint: 'Separate address spaces do not imply the same identity.', source: 'OSTEP Chapter 5: Process API' },
    { id: 'm02q6', level: 'Apply', prompt: 'A parent must print only after its child exits. Which change directly enforces this order?', choices: ['Add wait in the parent', 'Call fork twice', 'Remove exit', 'Increase the child PID'], answer: 0, explanation: 'wait blocks the parent until a child changes to a collectable state.', hint: 'Use explicit synchronization, not timing.', source: 'OSTEP Chapter 5: Process API' },
    { id: 'm02q7', level: 'Analyze', prompt: 'Why can output order vary when parent and child both print immediately after fork?', choices: ['The file contents select the order', 'The scheduler may run either ready process first', 'fork sorts output alphabetically', 'Both prints are one atomic instruction'], answer: 1, explanation: 'Both processes are runnable and their execution order is a scheduling decision.', hint: 'No wait or other ordering edge has been established.', source: 'OSTEP Chapters 4–5' },
    { id: 'm02q8', level: 'Evaluate', prompt: 'Which trace most clearly explains a two-command shell pipeline?', choices: ['Only the final text', 'PIDs plus fork/exec/wait and file-descriptor redirection events', 'Only CPU temperature', 'Directory permissions only'], answer: 1, explanation: 'The process and descriptor events reveal creation, program replacement, connection, and collection.', hint: 'Choose evidence that shows both control flow and I/O setup.', source: 'OSTEP Chapter 5: Process API' }
  ],
  m03: [
    { id: 'm03q4', level: 'Remember', prompt: 'Response time measures what interval?', choices: ['Arrival to first run', 'Arrival to completion', 'First run to disk flush', 'Context switch to page fault'], answer: 0, explanation: 'Response time is the delay from arrival until the job first receives CPU service.', hint: 'Interactive users notice the first visible service.', source: 'OSTEP Chapters 7–10: CPU Scheduling' },
    { id: 'm03q5', level: 'Understand', prompt: 'Why can FCFS exhibit a convoy effect?', choices: ['A long job can delay many short jobs behind it', 'It always preempts too often', 'It predicts future bursts exactly', 'It runs no jobs'], answer: 0, explanation: 'A long non-preemptive job at the front makes short arrivals wait.', hint: 'Picture one long checkout followed by many short ones.', source: 'OSTEP Chapter 7: Scheduling Introduction' },
    { id: 'm03q6', level: 'Apply', prompt: 'Lottery-scheduled job A owns 75 tickets and B owns 25. Over many draws, what service share is expected?', choices: ['A about 75% and B about 25%', 'Each exactly 50%', 'A always 100%', 'Ticket counts affect only memory'], answer: 0, explanation: 'Lottery scheduling makes each ticket equally likely, so long-run service is proportional to 75:25, while short runs can vary.', hint: 'Convert each ticket count to a fraction of the 100-ticket total.', source: 'OSTEP Chapter 9: Proportional Share' },
    { id: 'm03q7', level: 'Analyze', prompt: 'Why can moving a process between CPUs reduce performance even when both CPUs are idle enough?', choices: ['The process may lose warm cache state and incur migration cost', 'A process can never run on another CPU', 'Migration removes its virtual address space', 'It disables timer interrupts'], answer: 0, explanation: 'Multiprocessor scheduling balances load against cache affinity; migration can discard useful per-CPU cache locality.', hint: 'Consider what hardware state is local to one CPU.', source: 'OSTEP Chapter 10: Multiprocessor Scheduling' },
    { id: 'm03q8', level: 'Evaluate', prompt: 'Which evidence is sufficient to compare two schedulers on one workload?', choices: ['Policy names alone', 'Arrival/burst assumptions, Gantt traces, computed metrics, and stated objective', 'One unexplained average', 'The source-code line count'], answer: 1, explanation: 'A defensible comparison exposes inputs, execution, metric arithmetic, and the goal being optimized.', hint: 'Choose evidence that makes the conclusion reproducible.', source: 'OSTEP Chapters 7–10; Winter 2026 HW1/PA2 basis' }
  ],
  m04: [
    { id: 'm04q4', level: 'Apply', prompt: 'Which C memory-management error occurs when code accesses a heap object after passing it to free?', choices: ['Use-after-free', 'External fragmentation only', 'A scheduler convoy', 'A TLB hit'], answer: 0, explanation: 'After free, the pointer no longer designates storage the program may safely access; reading or writing through it is undefined behavior.', hint: 'Ownership of the allocated object has ended.', source: 'OSTEP Chapter 14: Memory API' },
    { id: 'm04q5', level: 'Understand', prompt: 'Why can stack and heap use separate segments?', choices: ['They have different logical roles and growth behavior', 'Segments eliminate all fragmentation', 'They must share one base', 'The stack is always on disk'], answer: 0, explanation: 'Separate bases, bounds, permissions, and growth directions fit distinct regions.', hint: 'Think about region-specific translation and growth.', source: 'OSTEP Chapter 16: Segmentation' },
    { id: 'm04q6', level: 'Apply', prompt: 'Base is 8000 and bound is 1000. What happens to virtual address 1200?', choices: ['Physical 9200', 'Physical 6800', 'Protection fault', 'TLB hit'], answer: 2, explanation: 'The offset 1200 exceeds the 1000-byte bound, so translation must fault.', hint: 'Check validity before adding the base.', source: 'OSTEP Chapter 15: Address Translation' },
    { id: 'm04q7', level: 'Analyze', prompt: 'Which memory map is most vulnerable to external fragmentation?', choices: ['Variable-sized segments allocated among holes', 'Fixed-size page frames', 'One register value', 'A contiguous disk log only'], answer: 0, explanation: 'Variable-size allocation leaves separated free holes even when total free space is adequate.', hint: 'External fragmentation concerns unusable gaps between allocations.', source: 'OSTEP Chapter 16: Segmentation' },
    { id: 'm04q8', level: 'Evaluate', prompt: 'A translation worksheet lists only final physical addresses. What crucial evidence is missing?', choices: ['Validity/bounds checks and arithmetic', 'The student name font', 'CPU fan speed', 'The directory color'], answer: 0, explanation: 'A final number cannot show whether protection was checked or how the mapping was derived.', hint: 'Choose evidence that distinguishes a valid translation from a lucky guess.', source: 'OSTEP Chapters 15–16; Winter 2026 HW2 basis' }
  ],
  m05: [
    { id: 'm05q4', level: 'Remember', prompt: 'Which virtual-address field remains unchanged through paging translation?', choices: ['VPN', 'Page offset', 'PFN', 'Valid bit'], answer: 1, explanation: 'Translation replaces the virtual page number with a physical frame number and preserves the offset.', hint: 'Position within the page is the same within the frame.', source: 'OSTEP Chapter 18: Paging' },
    { id: 'm05q5', level: 'Understand', prompt: 'What information does a valid page-table entry normally provide?', choices: ['A physical frame and access metadata', 'A process arrival time', 'A directory pathname only', 'A CPU burst prediction'], answer: 0, explanation: 'The PTE maps a VPN to a PFN and includes bits such as valid, writable, or referenced.', hint: 'It supports both translation and protection.', source: 'OSTEP Chapters 18–20' },
    { id: 'm05q6', level: 'Apply', prompt: 'For 1 KiB pages, how many low-order offset bits does an address have?', choices: ['8', '10', '12', '16'], answer: 1, explanation: '1 KiB is 1024 bytes, or 2^10, so ten bits select a byte within the page.', hint: 'Express the page size as a power of two.', source: 'OSTEP Chapter 18: Paging' },
    { id: 'm05q7', level: 'Analyze', prompt: 'A TLB miss finds a valid resident PTE. What happens next conceptually?', choices: ['The translation is installed and access can retry', 'The process must always terminate', 'The disk is reformatted', 'The page offset is discarded'], answer: 0, explanation: 'The system completes page-table lookup, caches the translation, and retries without a disk page-in.', hint: 'A cache miss does not imply the data is absent from memory.', source: 'OSTEP Chapter 19: TLBs' },
    { id: 'm05q8', level: 'Evaluate', prompt: 'Which design best fits a very sparse virtual address space?', choices: ['A fully allocated linear table regardless of use', 'A multi-level table that omits empty subtrees', 'No translation protection', 'One TLB entry per byte'], answer: 1, explanation: 'Multi-level tables trade extra walks for allocating page-table structures only where mappings exist.', hint: 'Optimize metadata space for large unused regions.', source: 'OSTEP Chapter 20: Smaller Tables' }
  ],
  m06: [
    { id: 'm06q4', level: 'Remember', prompt: 'Which bit helps Clock approximate recent use?', choices: ['Reference/use bit', 'Executable filename bit', 'PID parity bit', 'Directory link count'], answer: 0, explanation: 'Clock examines and clears a reference bit to give recently used pages another chance.', hint: 'The hardware records whether the page was accessed.', source: 'OSTEP Chapter 22: Replacement Policy' },
    { id: 'm06q5', level: 'Understand', prompt: 'Why may a dirty victim page cost more to evict than a clean one?', choices: ['It may require a write before reuse of the frame', 'It has no virtual address', 'It cannot be referenced', 'It is always executable'], answer: 0, explanation: 'Modified data must be preserved to backing storage before its frame is repurposed.', hint: 'Clean data already has an up-to-date backing copy.', source: 'OSTEP Chapters 21–22' },
    { id: 'm06q6', level: 'Apply', prompt: 'Frames contain A, B, C in FIFO order, and D misses. Which page does FIFO evict?', choices: ['A', 'B', 'C', 'D'], answer: 0, explanation: 'FIFO removes the page that entered memory earliest, which is A.', hint: 'FIFO ignores recent access and uses arrival order.', source: 'OSTEP Chapter 22: Replacement Policy' },
    { id: 'm06q7', level: 'Analyze', prompt: 'Why can adding memory sometimes increase FIFO faults on a particular trace?', choices: ['Belady’s anomaly', 'DMA coherence', 'Priority inheritance', 'Write-ahead logging'], answer: 0, explanation: 'FIFO lacks the stack property and can exhibit Belady’s anomaly.', hint: 'This counterintuitive behavior is associated with FIFO.', source: 'OSTEP Chapter 22: Replacement Policy' },
    { id: 'm06q8', level: 'Evaluate', prompt: 'Which experiment best supports a replacement-policy conclusion?', choices: ['One trace with no frame count', 'Multiple traces and frame counts with fault tables and locality interpretation', 'Policy names only', 'A compiler warning'], answer: 1, explanation: 'Replacement behavior depends on trace locality and available frames, so both must be varied and reported.', hint: 'Avoid claiming a universal winner from one unexplained run.', source: 'OSTEP Chapter 22; Winter 2026 HW2 basis' }
  ],
  m07: [
    { id: 'm07q4', level: 'Remember', prompt: 'Which execution state is private to each thread?', choices: ['Process address space', 'Thread stack and register context', 'All open files', 'Global variables'], answer: 1, explanation: 'Threads share process resources but require individual stacks and registers.', hint: 'Each thread must resume its own call chain.', source: 'OSTEP Chapters 26–27; lecture 2-1' },
    { id: 'm07q5', level: 'Understand', prompt: 'What makes an operation data-racy?', choices: ['Concurrent conflicting access to shared state without required synchronization', 'Any use of two local variables', 'Calling printf once', 'A deterministic test'], answer: 0, explanation: 'A data race involves unsynchronized conflicting accesses where at least one is a write.', hint: 'Identify shared location, overlap, and write access.', source: 'OSTEP Chapter 26; lecture 2-1' },
    { id: 'm07q6', level: 'Apply', prompt: 'Two threads each execute load counter=4, add one, store. What final value can result?', choices: ['Exactly 6 only', '5 due to a lost update', '4 only', 'A page fault necessarily'], answer: 1, explanation: 'Both may store 5 after reading 4, losing one logical increment.', hint: 'Interleave the three machine-level steps.', source: 'OSTEP Chapter 26; lecture 2-1' },
    { id: 'm07q7', level: 'Analyze', prompt: 'Why does adding print statements sometimes hide a race?', choices: ['The changed timing alters the observed schedule', 'Printing makes updates atomic by definition', 'The compiler deletes threads', 'The race becomes a file link'], answer: 0, explanation: 'Instrumentation perturbs timing and may make a harmful interleaving less likely without fixing it.', hint: 'Observation can change timing in concurrent programs.', source: 'OSTEP Chapter 26; lecture 2-1' },
    { id: 'm07q8', level: 'Evaluate', prompt: 'Which claim about a race fix is strongest?', choices: ['It passed once', 'The shared invariant is protected on every access and stress/sanitizer evidence agrees', 'The output looked plausible', 'The program runs faster'], answer: 1, explanation: 'Correctness reasoning plus dynamic evidence is stronger than either a single run or a tool alone.', hint: 'Combine an invariant argument with observations.', source: 'OSTEP Chapters 26–27; Winter 2026 HW3 basis' }
  ],
  m08: [
    { id: 'm08q4', level: 'Remember', prompt: 'What code region should a mutex surround?', choices: ['The critical section that accesses a protected invariant', 'Every comment', 'Only process creation', 'A page-table offset'], answer: 0, explanation: 'All operations that can violate the shared invariant must follow the same lock discipline.', hint: 'Protect the state transition, not an arbitrary line.', source: 'OSTEP Chapters 28–29; lecture 2-2' },
    { id: 'm08q5', level: 'Understand', prompt: 'Why can a spin lock waste CPU?', choices: ['A waiting thread repeatedly checks instead of sleeping', 'It writes files', 'It disables registers', 'It creates page tables'], answer: 0, explanation: 'Busy waiting consumes execution cycles while the lock holder runs or is descheduled.', hint: 'Consider a long wait on one CPU.', source: 'OSTEP Chapter 28; lecture 2-2' },
    { id: 'm08q6', level: 'Apply', prompt: 'A list length and its links must agree. Which locking rule is safest?', choices: ['Update both while holding the lock that protects the list invariant', 'Lock only after the update', 'Use unrelated locks without an order', 'Rely on sleep'], answer: 0, explanation: 'The whole invariant-changing transition must be mutually exclusive.', hint: 'Readers must never observe a half-updated representation.', source: 'OSTEP Chapters 28–29; lecture 2-2' },
    { id: 'm08q7', level: 'Analyze', prompt: 'A lock protects writes but readers access the same variable unlocked. What is wrong?', choices: ['The protection discipline is incomplete', 'Readers are always atomic and ordered', 'The variable becomes persistent', 'The scheduler fixes it'], answer: 0, explanation: 'Every conflicting access participating in the invariant needs compatible synchronization.', hint: 'A lock is effective only when all participants follow it.', source: 'OSTEP Chapter 28; lecture 2-2' },
    { id: 'm08q8', level: 'Evaluate', prompt: 'When is a coarse-grained lock a reasonable first design?', choices: ['When correctness and simplicity dominate and measured contention is acceptable', 'When no state is shared', 'When deadlock must be guaranteed', 'When the lock is never released'], answer: 0, explanation: 'A simple locking proof is valuable; refine granularity only with evidence that contention matters.', hint: 'Start from a correct invariant-preserving design.', source: 'OSTEP Chapter 29; lecture 2-2' }
  ],
  m09: [
    { id: 'm09q4', level: 'Remember', prompt: 'Which operation increments a semaphore and may wake a waiter?', choices: ['post', 'wait', 'fork', 'exec'], answer: 0, explanation: 'sem_post returns a unit and can unblock a waiting thread.', hint: 'This is sometimes called V.', source: 'OSTEP Chapter 31; lecture 2-4' },
    { id: 'm09q5', level: 'Understand', prompt: 'Why must condition-variable code test a predicate rather than treat a signal as stored state?', choices: ['The predicate describes the actual protected state; a signal is only a notification', 'Signals write the file system', 'Predicates disable mutexes', 'A signal always counts resources'], answer: 0, explanation: 'Correctness depends on state under the mutex, and wakeups only prompt rechecking.', hint: 'Ask what remains true if wakeups are early or shared.', source: 'OSTEP Chapter 30; lecture 2-3' },
    { id: 'm09q6', level: 'Apply', prompt: 'A buffer has capacity 4 and currently 0 items. What should a consumer do?', choices: ['Wait in a loop until count > 0 while using the mutex/condition', 'Read slot 0 immediately', 'Sleep one second and assume success', 'Increment capacity'], answer: 0, explanation: 'The consumer cannot remove an item until the protected nonempty predicate holds.', hint: 'Express the condition on buffer state.', source: 'OSTEP Chapter 30; lecture 2-3' },
    { id: 'm09q7', level: 'Analyze', prompt: 'Why is signaling a condition while changing its predicate without the mutex risky?', choices: ['A waiter can miss or observe an inconsistent state transition', 'It makes the semaphore negative by definition', 'It changes virtual addresses', 'It forces DMA'], answer: 0, explanation: 'Predicate changes and notification need a consistent synchronization protocol.', hint: 'Reason about the check-to-sleep race.', source: 'OSTEP Chapter 30; lecture 2-3' },
    { id: 'm09q8', level: 'Evaluate', prompt: 'For a pool of three identical resources, which starting primitive best models availability?', choices: ['Counting semaphore initialized to 3', 'Condition variable with no predicate or mutex', 'Unlocked Boolean', 'Timer interrupt'], answer: 0, explanation: 'The count directly represents three available units and wait/post acquire/release one.', hint: 'Choose a primitive whose state is a resource count.', source: 'OSTEP Chapter 31; lecture 2-4' }
  ],
  m10: [
    { id: 'm10q4', level: 'Remember', prompt: 'What does hold-and-wait mean?', choices: ['A thread holds one resource while waiting for another', 'All locks are free', 'A process is sleeping without resources', 'A page is clean'], answer: 0, explanation: 'Hold-and-wait is one necessary deadlock condition.', hint: 'The participant retains something while requesting more.', source: 'OSTEP Chapter 32; lecture 2-5' },
    { id: 'm10q5', level: 'Understand', prompt: 'How does a global lock order prevent deadlock?', choices: ['It prevents cycles in acquisition dependencies', 'It removes mutual exclusion', 'It guarantees fairness', 'It disables waiting'], answer: 0, explanation: 'If every thread follows one strict order, a circular wait cannot form.', hint: 'A cycle would require an order contradiction.', source: 'OSTEP Chapter 32; lecture 2-5' },
    { id: 'm10q6', level: 'Apply', prompt: 'T1 holds A and waits for B; T2 holds B and waits for A. What graph evidence exists?', choices: ['A wait-for cycle', 'A TLB hit', 'A journal commit', 'A clean shutdown'], answer: 0, explanation: 'T1→T2 and T2→T1 form a cycle consistent with deadlock.', hint: 'Draw who waits for whom.', source: 'OSTEP Chapter 32; lecture 2-5' },
    { id: 'm10q7', level: 'Analyze', prompt: 'Two threads repeatedly release and reacquire in response to each other but finish no work. What is this?', choices: ['Livelock', 'Starvation only', 'Demand paging', 'Journaling'], answer: 0, explanation: 'They remain active and change state but make no useful progress.', hint: 'Unlike deadlock, the participants are not simply blocked.', source: 'OSTEP Chapter 32; lecture 2-5' },
    { id: 'm10q8', level: 'Evaluate', prompt: 'Which deadlock report is most actionable?', choices: ['“It hung”', 'Thread stacks, held/waited locks, wait-for graph, and a reproducible trigger', 'A screenshot of the editor title', 'Only elapsed time'], answer: 1, explanation: 'Those artifacts expose the dependency cycle and the execution that produced it.', hint: 'Choose evidence that identifies participants and resources.', source: 'OSTEP Chapter 32; lecture 2-5' }
  ],
  m11: [
    { id: 'm11q4', level: 'Remember', prompt: 'What usually notifies the CPU that an asynchronous device operation completed?', choices: ['Interrupt', 'Page offset', 'Hard link', 'Mutex owner'], answer: 0, explanation: 'Devices commonly raise interrupts so the kernel can handle completion.', hint: 'The CPU need not poll continuously.', source: 'OSTEP Chapter 36; lecture 3-1' },
    { id: 'm11q5', level: 'Understand', prompt: 'Why does a process often block during slow I/O?', choices: ['The CPU can run other ready work while the device progresses', 'Blocking makes the device instantaneous', 'It removes the driver', 'It converts the file to memory'], answer: 0, explanation: 'Blocking avoids spending CPU cycles on a request that cannot yet complete.', hint: 'Separate CPU service from device latency.', source: 'OSTEP Chapter 36; lecture 3-1' },
    { id: 'm11q6', level: 'Apply', prompt: 'Which trace line most directly demonstrates a user/kernel boundary for file input?', choices: ['read(3, buffer, 64) = 12', 'counter++', 'int x;', 'a source-code comment'], answer: 0, explanation: 'strace records the read system call, descriptor, requested bytes, and return value.', hint: 'Look for a system-call name and result.', source: 'OSTEP Chapter 36; lecture 3-1' },
    { id: 'm11q7', level: 'Analyze', prompt: 'Why can interrupts outperform polling for a slow unpredictable device?', choices: ['The CPU can perform other work until completion notification', 'Interrupts eliminate driver code', 'Polling has no status checks', 'DMA requires polling forever'], answer: 0, explanation: 'Interrupts avoid repeated checks during a long or uncertain wait.', hint: 'Compare useful CPU work during the wait.', source: 'OSTEP Chapter 36; lecture 3-1' },
    { id: 'm11q8', level: 'Evaluate', prompt: 'Which claim about DMA is appropriately bounded?', choices: ['DMA reduces CPU involvement in bulk transfer but setup and completion handling still cost work', 'DMA makes I/O free', 'DMA removes memory', 'DMA prevents every interrupt'], answer: 0, explanation: 'DMA changes who moves data; it does not eliminate setup, coordination, or completion costs.', hint: 'Avoid an absolute performance claim.', source: 'OSTEP Chapter 36; lecture 3-1' }
  ],
  m12: [
    { id: 'm12q4', level: 'Remember', prompt: 'What does an inode number identify within a file system?', choices: ['A file-system object’s metadata record', 'A process scheduling priority', 'A CPU register', 'A TLB entry only'], answer: 0, explanation: 'Directory names map to inode-backed objects that hold metadata and block pointers.', hint: 'It is distinct from a pathname.', source: 'OSTEP Chapter 39; lecture 3-3' },
    { id: 'm12q5', level: 'Understand', prompt: 'Why can two hard-link pathnames show the same inode number?', choices: ['Both directory entries refer to the same underlying object', 'They are symbolic links necessarily', 'The shell copied the file contents', 'Inodes are process IDs'], answer: 0, explanation: 'A hard link adds another name-to-inode mapping rather than another file object.', hint: 'Names and objects are separate.', source: 'OSTEP Chapter 39; lecture 3-3' },
    { id: 'm12q6', level: 'Apply', prompt: 'After deleting one of two hard links, what normally happens to the file data?', choices: ['It remains reachable through the other hard link', 'It must vanish immediately', 'It becomes a process', 'It moves to the TLB'], answer: 0, explanation: 'Removing one name decrements the link count; the object remains while another link/open reference exists.', hint: 'Deletion removes a directory entry first.', source: 'OSTEP Chapter 39; lecture 3-3' },
    { id: 'm12q7', level: 'Analyze', prompt: 'A symbolic link breaks after its target is renamed. Why?', choices: ['It stores a pathname that no longer resolves', 'It stores the same inode directly', 'It pins the target open forever', 'It changed the scheduler'], answer: 0, explanation: 'A symlink contains a path, so later resolution can fail after a rename or removal.', hint: 'Contrast symbolic and hard links.', source: 'OSTEP Chapter 39; lecture 3-3' },
    { id: 'm12q8', level: 'Evaluate', prompt: 'Which experiment best demonstrates the difference between names and file objects?', choices: ['Compare inode/link counts before and after hard-link creation and unlink operations', 'Compile an unrelated program', 'Change CPU priority', 'Measure page faults only'], answer: 0, explanation: 'The metadata and behavior expose multiple names referencing one object.', hint: 'Use `ls -li` or `stat` with controlled link operations.', source: 'OSTEP Chapter 39; lecture 3-3' }
  ],
  m13: [
    { id: 'm13q4', level: 'Remember', prompt: 'What is the purpose of a file-system journal?', choices: ['Record intended updates so recovery can restore consistency', 'Schedule CPU bursts', 'Translate virtual addresses', 'Create threads'], answer: 0, explanation: 'A journal records update intent/transactions before or alongside home-location writes.', hint: 'It supports recovery after an interrupted update.', source: 'OSTEP Chapter 42; lecture 3-5' },
    { id: 'm13q5', level: 'Understand', prompt: 'Why is update ordering important during a crash?', choices: ['A partial sequence can leave metadata pointing to uninitialized or unaccounted blocks', 'Disk writes always occur atomically as one file-system transaction', 'Ordering changes process IDs', 'It removes locality'], answer: 0, explanation: 'Multi-write invariants can be violated if only a prefix reaches stable storage.', hint: 'Consider allocation metadata, inode pointers, and data blocks.', source: 'OSTEP Chapters 40–42; lectures 3-4/3-5' },
    { id: 'm13q6', level: 'Apply', prompt: 'A file append must survive a reported successful save. Which evidence is strongest?', choices: ['Run, request the required durability operation, simulate/recover under the approved lab method, and verify content', 'Observe the editor buffer only', 'Check the filename color', 'Assume close always reached disk'], answer: 0, explanation: 'Durability needs a defined persistence point and post-recovery observation, not just an in-memory view.', hint: 'Distinguish visibility from stable storage.', source: 'OSTEP Chapter 42; lecture 3-5' },
    { id: 'm13q7', level: 'Analyze', prompt: 'Why can write-back caching improve performance but complicate crash behavior?', choices: ['Updates may be delayed and reach storage in a different order', 'It disables all writes', 'It converts files to threads', 'It makes every write synchronous'], answer: 0, explanation: 'Buffering batches/reorders writes, so consistency depends on protocols such as ordering, barriers, or journaling.', hint: 'Performance comes from delaying or grouping physical writes.', source: 'OSTEP Chapters 40–42; lecture 3-5' },
    { id: 'm13q8', level: 'Evaluate', prompt: 'Which claim about an FFS-style block-group policy is defensible?', choices: ['Keeping related inode and data blocks near one another can improve locality for matching workloads, but placement and workload still matter', 'It guarantees every file operation takes one disk access', 'It eliminates fragmentation for every workload', 'It makes crash recovery unnecessary'], answer: 0, explanation: 'FFS uses placement policy to improve locality, but workload, free-space shape, file size, caching, and device behavior bound the benefit.', hint: 'Prefer a conditional locality claim over an absolute performance promise.', source: 'OSTEP Chapter 41: Fast File System' }
  ]
};
